### PR TITLE
Fixed cancel errors

### PR DESCRIPTION
**Pull request by serge1peshcoff**
When cancelling the request with axios, the nprogress bar gets stuck. I've tweaked it so it'd increase if the error is the cancellation error.

(The only change I made is in src/index.js, the others were auto-generated)

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@fundon can you look into that?

**Comment by lucianobosco** [comment]
Hey @serge1peshcoff , how can I make use of your fix? I'm facing this same issue 2 years later. 
This package seems to be completely deprecated. Do you have any repository to use or fork?
Thanks!

**Comment by serge1peshcoff** [comment]
@lucianobosco I ended up copying the whole codebase to my project instead and changing it there :D

**Comment by fundon** [comment]
@serge1peshcoff  Should I release new version?

**Comment by lucianobosco** [comment]
Hi @fundon , I'm sorry to intrude on the conversation but it would be great to have a new version to be updated via npm, otherwise, we have to pull your updates and compile the package. Please correct me if I'm wrong, but I guess this is the best and most elegant solution.

**Comment by fundon** [comment]
Landed in [v0.2.0](https://github.com/vue-bulma/nprogress/tree/v0.2.0).

**Comment by lucianobosco** [comment]
Awesome! Now I can enjoy this feature again! Thank you so much, it's working as expected

**Pull request merged**
