### PR TITLE
Make it compatible with browsers (add dist)

### PR DESCRIPTION
**Pull request by abou7mied**
Thanks for this awsome plugin, but an error occurred when I tried to require and bundle it with webpack
`unexpected token import` at:
`import nprogress from 'nprogress'`

I'm using babel compiler but not for `node_modules` so I forked your plugin and made a build file to export JS file compatible with browsers

### CODE REVIEW

**Comment by fundon** [comment]
Nice!

git rebase, please.

**Comment by abou7mied** [comment]
I'm sorry, but you haven't made any commits so why do I need to rebase ?

I'm doing some extra changes and will push it to the fork soon, please don't merge now, I will comment when I finish

**Comment by fundon** [comment]
I mean that merging two commits to one http://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one. 😁

> I'm doing some extra changes and will push it to the fork soon, please don't merge now, I will comment when I finish

Cool!

**Comment by abou7mied** [comment]
Aha nice!
I just made some commits and merged them into one.

Now you can review the changes and merge.

**Pull request merged**
